export {default as PeoplePage} from './people-page'
export {default as PlanetsPage} from './planets-page'
export {default as StarshipsPage} from './starships-page'
export {default as LoginPage} from './login-page'
export {default as SecretPage} from './secret-page'
